### ISSUE TITLE
Ne pas pouvoir "déflaguer" si une seule case restante

### ISSUE THREAD

**Issue by geraldroussel** [aboudoux/DemineurOnline#4]
S'il y a 2 cases restantes pour une seule bombe et que les 2 cases sont valables, il est possible de flaguer la première case puis, si ça ne pète pas, on la déflague et on flague l'autre pour gagner !

Dans ce cas (et uniquement celui-là), il faudrait afficher un message différent du genre "pas de bol !" au lieu de "boom!" et continuer le process identique (boite de saisie pour highscrore, bouton restart,...etc).

GéGé ;)

**Comment by aboudoux** [comment]
A mon avis, le plus simple est de faire en sorte que pour gagner, il faut que tous les drapeaux soient placés et que toutes les cases soient découvertes ?
